<div class="social-link">
<h4>Questions?</h4>
<div class="links"><a class="phone_link" href="skype:+1888123456?call">1-888-123-456</a><hr class="vertical">
<div class="social-icons"><a class="social-icon" href="https://www.facebook.com/" target="_blank" rel="noopener"><img src="{{media url="wysiwyg/icons/facebook-logo.png"}}" alt=""></a> <a class="social-icon" href="https://twitter.com/?lang=vi" target="_blank" rel="noopener"><img src="{{media url="wysiwyg/icons/twitter.png"}}" alt=""></a> <a class="social-icon" href="https://www.linkedin.com/" target="_blank" rel="noopener"><img src="{{media url="wysiwyg/icons/linkedin.png"}}" alt=""></a> <a class="social-icon" href="https://www.instagram.com/?hl=vi" target="_blank" rel="noopener"><img src="{{media url="wysiwyg/icons/instagram-logo.png"}}" alt=""></a></div>
</div>
</div>