<section class="partners-panel">
    <div class="container">
        <div class="vendor">
            <div><img src='<?php echo $this->getViewFileUrl('images/1.png'); ?>' alt="logo"></div>
            <div><img src='<?php echo $this->getViewFileUrl('images/2.png'); ?>' alt="logo"></div>
            <div><img src='<?php echo $this->getViewFileUrl('images/3.png'); ?>' alt="logo"></div>
            <div><img src='<?php echo $this->getViewFileUrl('images/4.png'); ?>' alt="logo"></div>
            <div><img src='<?php echo $this->getViewFileUrl('images/5.png'); ?>' alt="logo"></div>
            <div><img src='<?php echo $this->getViewFileUrl('images/6.png'); ?>' alt="logo"></div>
        </div>

    </div>
</section>