<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
/** @var \Magento\Catalog\Helper\Output $_helper */
$_helper = $block->getData('outputHelper');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
?>
<?php if (!$_productCollection->count()):?>
    <div class="message info empty">
        <div><?= $escaper->escapeHtml(__('We can\'t find products matching the selection.')) ?></div>
    </div>
<?php else:?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    
    <?php if( $viewMode == 'grid'):?>
        <!--CHECK VIEWMODE IS GRID-->
        <div class="products wrapper <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?>">
            <ol class="products list items product-items">
                <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                <?php foreach ($_productCollection as $_product):?>
                <li class="item product product-item">
                    <div class="product-item-info"
                        id="product-item-info_<?= /* @noEscape */ $_product->getId() ?>"
                        data-container="product-<?= /* @noEscape */ $viewMode ?>">
                        <?php
                        $productImage = $block->getImage($_product, $imageDisplayArea);
                        if ($pos != null) {
                            $position = 'left:' . $productImage->getWidth() . 'px;'
                                . 'top:' . $productImage->getHeight() . 'px;';
                        }
                        ?>
                        <?php // Product Image ?>
                    
                            <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>"
                            class="product photo product-item-photo"
                            tabindex="-1">
                                <div class="container-hover-image">
                                    <?= $productImage->toHtml() ?>
                                    <?php $product = $objectManager->create('Magento\Catalog\Model\Product')->load($_product->getId());
                                    $images = $product->getMediaGalleryImages();
                                    $tmp = 0;
                                    foreach($images as $child){
                                        if($tmp == 1){?>
                                    <!-- <img src="img_avatar.png" alt="Avatar" class="image" style="width:100%"> -->
                                    <div class="middle">
                                        <img src="<?php echo $child->getUrl(); ?>" class="image-hung" >
                                    </div>
                                    <?php } $tmp++; } ?>
                                </div>
                            </a>
                            <!-- take image2 for hover-->
                        
                        <div class="product details product-item-details">
                            <?php
                                $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                            ?>
                            <strong class="product name product-item-name">
                                <div class="row">
                                    <div class="col-8" style="margin:0;padding:0;display:inline-flex;">
                                    <a class="product-item-link"
                                        href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>">
                                            <?=/* @noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name')?>
                                        </a>
                                    </div>
                                    <div class="col-4" style="margin:0;padding:0;text-align: right;">
                                    <div data-role="add-to-links" class="actions-secondary">
                                            <?php if ($addToBlock = $block->getChildBlock('addto')):?>
                                                <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                </div>
                            </strong>
                            <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                            <?= /* @noEscape */ $block->getProductPrice($_product) ?>
                            <?php if ($_product->isAvailable()):?>
                                <?= $block->getProductDetailsHtml($_product) ?>
                            <?php endif; ?>

                            <div class="product-item-inner">
                                <div class="product actions product-item-actions">
                                    <div class="actions-primary">
                                        <?php if ($_product->isSaleable()):?>
                                            <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                            <form data-role="tocart-form"
                                                data-product-sku="<?= $escaper->escapeHtml($_product->getSku()) ?>"
                                                action="<?= $escaper->escapeUrl($postParams['action']) ?>"
                                                method="post">
                                                <input type="hidden"
                                                    name="product"
                                                    value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
                                                <input type="hidden"
                                                    name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>"
                                                    value="<?=
                                                    /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED]
                                                        ?>">
                                                <?= $block->getBlockHtml('formkey') ?>
                                                <button type="submit"
                                                        title="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                        class="action tocart primary">
                                                    <span><?= $escaper->escapeHtml(__('Add to Cart')) ?></span>
                                                </button>
                                            </form>
                                        <?php else:?>
                                            <?php if ($_product->isAvailable()):?>
                                                <div class="stock available">
                                                    <span><?= $escaper->escapeHtml(__('In stock')) ?></span></div>
                                            <?php else:?>
                                                <div class="stock unavailable">
                                                    <span><?= $escaper->escapeHtml(__('Out of stock')) ?></span></div>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </div>
                                    <?= strpos($pos, $viewMode . '-primary') ?
                                        /* @noEscape */ $secureRenderer->renderStyleAsTag(
                                            $position,
                                            'product-item-info_' . $_product->getId() . ' div.actions-primary'
                                        ) : '' ?>
                                    <?= strpos($pos, $viewMode . '-secondary') ?
                                        /* @noEscape */ $secureRenderer->renderStyleAsTag(
                                            $position,
                                            'product-item-info_' . $_product->getId() . ' div.actions-secondary'
                                        ) : '' ?>
                                </div>
                                <?php if ($showDescription):?>
                                    <div class="product description product-item-description">
                                        <?= /* @noEscape */ $_helper->productAttribute(
                                            $_product,
                                            $_product->getShortDescription(),
                                            'short_description'
                                        ) ?>
                                        <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>"
                                        title="<?= /* @noEscape */ $_productNameStripped ?>"
                                        class="action more"><?= $escaper->escapeHtml(__('Learn More')) ?></a>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                    <?= strpos($pos, $viewMode . '-actions') ?
                    /* @noEscape */ $secureRenderer->renderStyleAsTag(
                        $position,
                        'product-item-info_' . $_product->getId() . ' div.product-item-actions'
                    ) : '' ?>
                </li>
                <?php endforeach; ?>
            </ol>
        </div>
        <?= $block->getToolbarHtml() ?>
            <?php if (!$block->isRedirectToCartEnabled()):?>
                <script type="text/x-magento-init">
                {
                    "[data-role=tocart-form], .form.map.checkout": {
                        "catalogAddToCart": {
                            "product_sku": "<?= $escaper->escapeJs($_product->getSku()) ?>"
                        }
                    }
                }
                </script>
            <?php endif; ?>
        <?php else: ?>
            <div class="products wrapper <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?>">
                <!--CHECK VIEWMODE IS LIST-->
                <ol class="products product-list-view list items product-items">
                    <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                    <?php foreach ($_productCollection as $_product):?>
                    <li class="item product product-item">
                        <div class="product-item-info"
                            id="product-item-info_<?= /* @noEscape */ $_product->getId() ?>"
                            data-container="product-<?= /* @noEscape */ $viewMode ?>">
                            <?php
                            $productImage = $block->getImage($_product, $imageDisplayArea);
                            if ($pos != null) {
                                $position = 'left:' . $productImage->getWidth() . 'px;'
                                    . 'top:' . $productImage->getHeight() . 'px;';
                            }
                            ?>
                            <?php // Product Image ?>
                            <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>"
                                class="product photo product-item-photo"
                                tabindex="-1">
                                    <div class="container-hover-image">
                                        <?= $productImage->toHtml() ?>
                                        <?php $product = $objectManager->create('Magento\Catalog\Model\Product')->load($_product->getId());
                                        $images = $product->getMediaGalleryImages();
                                        $tmp = 0;
                                        foreach($images as $child){
                                            if($tmp == 1){?>
                                        <!-- <img src="img_avatar.png" alt="Avatar" class="image" style="width:100%"> -->
                                        <div class="middle">
                                            <img src="<?php echo $child->getUrl(); ?>" class="image-hung" >
                                        </div>
                                        <?php } $tmp++; } ?>
                                    </div>
                                </a>
                            <div class="product details product-item-details">
                                <?php
                                    $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                ?>
                                <strong class="product name product-item-name">
                                    <div class="row">
                                        <a class="product-item-link"
                                        href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>">
                                            <?=/* @noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name')?>
                                        </a>
                                    </div>   
                                </strong>
                                <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                                <?php if ((int)$_product->getReviewsCount() == 0) : ?>
                                    <div class="abc">
                                        <div class="rating-summary" id="rating-summary-none">
                                            <div class="rating-result" title="0%">
                                                <span style="width: 0%;"><span>0%</span></span>
                                            </div>
                                        </div>
                                    </div>
                                <?php endif; ?>
                                <?php if ($_product->isAvailable()):?>
                                    <?= $block->getProductDetailsHtml($_product) ?>
                                <?php endif; ?>

                                <div class="product-item-inner">
                                    <div class="product actions product-item-actions">
                                        <?= strpos($pos, $viewMode . '-primary') ?
                                            /* @noEscape */ $secureRenderer->renderStyleAsTag(
                                                $position,
                                                'product-item-info_' . $_product->getId() . ' div.actions-primary'
                                            ) : '' ?>
                                        <?= strpos($pos, $viewMode . '-secondary') ?
                                            /* @noEscape */ $secureRenderer->renderStyleAsTag(
                                                $position,
                                                'product-item-info_' . $_product->getId() . ' div.actions-secondary'
                                            ) : '' ?>
                                    </div>
                                    <?php if ($showDescription):?>
                                        <div class="product description product-item-description">
                                            <?= /* @noEscape */ $_helper->productAttribute(
                                                $_product,
                                                $_product->getShortDescription(),
                                                'short_description'
                                            ) ?>
                                            <?php if( $_product->getShortDescription() == '')?>
                                                <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>"
                                                title="<?= /* @noEscape */ $_productNameStripped ?>"
                                                class="action more" style="color:#606DA6;text-decoration:none;"><?= $escaper->escapeHtml(__('Learn More')) ?></a>
                                            <?php else: ?>
                                                <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>"
                                                title="<?= /* @noEscape */ $_productNameStripped ?>"
                                                class="action more go-to-detail"><?= $escaper->escapeHtml(__('Go to detail =>>>')) ?></a>
                                        </div>
                                    <?php endif; ?>
                                    <?= /* @noEscape */ $block->getProductPrice($_product) ?>
                                    <div class="row">
                                        <div class="actions-primary">
                                            <?php if ($_product->isSaleable()):?>
                                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                <form data-role="tocart-form"
                                                    data-product-sku="<?= $escaper->escapeHtml($_product->getSku()) ?>"
                                                    action="<?= $escaper->escapeUrl($postParams['action']) ?>"
                                                    method="post">
                                                    <input type="hidden"
                                                        name="product"
                                                        value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
                                                    <input type="hidden"
                                                        name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>"
                                                        value="<?=
                                                        /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED]
                                                            ?>">
                                                    <?= $block->getBlockHtml('formkey') ?>
                                                    <button type="submit"
                                                            title="<?= $escaper->escapeHtmlAttr(__('ADD TO CART')) ?>"
                                                            class="action tocart primary add-tocart-listview">
                                                            <i class="icon-shopping-bag"></i><span style="padding-left:1rem;"><?= $escaper->escapeHtml(__('ADD TO CART')) ?></span>
                                                    </button>
                                                </form>
                                            <?php else:?>
                                                <?php if ($_product->isAvailable()):?>
                                                    <div class="stock available">
                                                        <span><?= $escaper->escapeHtml(__('In stock')) ?></span></div>
                                                <?php else:?>
                                                    <div class="stock unavailable">
                                                        <span><?= $escaper->escapeHtml(__('Out of stock')) ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                        <div data-role="add-to-links" class="actions-secondary">
                                            <?php if ($addToBlock = $block->getChildBlock('addto')):?>
                                                <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <?= strpos($pos, $viewMode . '-actions') ?
                        /* @noEscape */ $secureRenderer->renderStyleAsTag(
                            $position,
                            'product-item-info_' . $_product->getId() . ' div.product-item-actions'
                        ) : '' ?>
                    </li>
                    <?php endforeach; ?>
                </ol>
            </div>
            <?= $block->getToolbarHtml() ?>
            <?php if (!$block->isRedirectToCartEnabled()):?>
                <script type="text/x-magento-init">
                {
                    "[data-role=tocart-form], .form.map.checkout": {
                        "catalogAddToCart": {
                            "product_sku": "<?= $escaper->escapeJs($_product->getSku()) ?>"
                        }
                    }
                }
                </script>
            <?php endif; ?>
            <script>
                function myFunction() {
                var x = document.getElementById("myTopnav");
                if (x.className === "topnav") {
                        x.className += " responsive";
                    } else {
                        x.className = "topnav";
                    }
                }
            </script>
        <?php endif; ?>
<?php endif; ?>

