<?php
switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
    break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Complete the Look');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
    break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('WE FOUND OTHER PRODUCTS YOU MIGHT LIKE!');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;

            $showAddTo = false;
            $showCart = false;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItemCollection();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = count($block->getItems())) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItems();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $title = __('New Products');
            $items = $exist;

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
    break;

    case 'other':
    break;
}
?>

<?php if ($exist):?>
<div class="clearfix"></div>
    <?php if ($type == 'related' || $type == 'upsell'): ?>
        <?php if ($type == 'related'): ?>
            <div class="block <?= /* @escapeNotVerified */ $class ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?= /* @escapeNotVerified */ $limit ?>" data-shuffle="<?= /* @escapeNotVerified */ $shuffle ?>">
        <?php else: ?>
            <div class="block <?= /* @escapeNotVerified */ $class ?>" data-mage-init='{"upsellProducts":{}}' data-limit="<?= /* @escapeNotVerified */ $limit ?>" data-shuffle="<?= /* @escapeNotVerified */ $shuffle ?>">
        <?php endif; ?>
    <?php else: ?>
        <div class="block <?= /* @escapeNotVerified */ $class ?>">
    <?php endif; ?>
  
    <div class="block-content content" aria-labelledby="block-<?= /* @escapeNotVerified */ $class ?>-heading">        
        <?php if($type == 'upsell'):?>
        <div class="products wrapper products-<?= /* @escapeNotVerified */ $type ?>">
            <div class="block-title title">
                <strong id="block-<?= /* @escapeNotVerified */ $class ?>-heading" role="heading" aria-level="2"><?= /* @escapeNotVerified */ $title ?></strong>
            </div>
            <hr>
                <div id="owlcarousel_<?=$type?>"  class="products list items owl-carousel owl-theme owl-loaded">           
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item): ?>

                    <?php $available = ''; ?>
                    <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                        <?php if (!$_item->getRequiredOptions()): ?>
                            <?php $available = 'related-available'; ?>
                        <?php endif; ?>
                    <?php endif; ?>
                    <?php if ($type == 'related' || $type == 'upsell'): ?>
                        <?= /* @escapeNotVerified */ ($iterator++ == 1) ? '<div class="item product product-item" style="display: none;">' : '</div><div class="item product product-item" style="display: none;">' ?>
                    <?php else: ?>
                        <?= /* @escapeNotVerified */ ($iterator++ == 1) ? '<div class="item product product-item">' : '</div><div class="item product product-item">' ?>
                    <?php endif; ?>
                    <div class="product-upsell-hung product-item-info <?= /* @escapeNotVerified */ $available ?>">
                        <div class="zoom-image">
                            <?= /* @escapeNotVerified */ '<!-- ' . $image . '-->' ?>
                                <?php $finalPrice=$_item->getFinalPrice();
                                $price=$_item->getPrice();
                                if ($finalPrice<$price) { ?>
                                    <span class="discount_percent">
                                        <?php
                                        $saving=round(($finalPrice/$price)*100)-100;
                                        echo $saving . "%"; ?>
                                    </span>
                                <?php } ?>
                            <a href="<?= /* @escapeNotVerified */ $block->getProductUrl($_item) ?>" class="product photo product-item-photo">
                                <?= $block->getImage($_item, $image)->toHtml() ?>
                            </a>
                        </div>
                        
                        <?php if ($type != 'related'): ?>
                        <div class="product details product-item-details">
                            <strong class="product name product-item-name"><a class="product-item-link" title="<?= $block->escapeHtml($_item->getName()) ?>" href="<?= /* @escapeNotVerified */ $block->getProductUrl($_item) ?>">
                                <?= $block->escapeHtml($_item->getName()) ?></a>
                            </strong>
                            <?php if ($templateType): ?>
                                <?= $block->getReviewsSummaryHtml($_item, $templateType,false) ?>
                            <?php endif; ?>
                            <?php if ((int)$_item->getReviewsCount()==0) : ?>
                                <div class="rating-summary" id="rating-summary-none">
                                    <div class="rating-result" title="0%">
                                        <span style="width: 0%;"><span>0%</span></span>
                                    </div>
                                </div>
                            <?php endif; ?>
                            <?= /* @escapeNotVerified */ $block->getProductPrice($_item) ?>
                                <?php if ($canItemsAddToCart && !$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                                    <?php if (!$_item->getRequiredOptions()): ?>
                                        <div class="field choice related">
                                            <input type="checkbox" class="checkbox related" id="related-checkbox<?= /* @escapeNotVerified */ $_item->getId() ?>" name="related_products[]" value="<?= /* @escapeNotVerified */ $_item->getId() ?>" />
                                            <label class="label" for="related-checkbox<?= /* @escapeNotVerified */ $_item->getId() ?>"><span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span></label>
                                        </div>
                                    <?php endif; ?>
                                <?php endif; ?>

                                <?php if ($showAddTo || $showCart): ?>
                                    <!--<div class="product actions product-item-actions">
                                        <?php if ($showCart): ?>
                                            <div class="actions-primary">
                                                <?php if ($_item->isSaleable()): ?>
                                                    <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                        <button class="action tocart primary" data-mage-init='{"redirectUrl": {"url": "<?= /* @escapeNotVerified */ $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?= /* @escapeNotVerified */ __('Add to Cart') ?>">
                                                            <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                                        </button>
                                                    <?php else: ?>
                                                        <?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                        $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                        ?>
                                                        <button class="action tocart primary"
                                                                data-post='<?= /* @escapeNotVerified */ $postData ?>'
                                                                type="button" title="<?= /* @escapeNotVerified */ __('Add to Cart') ?>">
                                                            <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                                        </button>
                                                    <?php endif; ?>
                                                <?php else: ?>
                                                    <?php if ($_item->getIsSalable()): ?>
                                                        <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                                                    <?php else: ?>
                                                        <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>

                                        <?php if ($showAddTo): ?>
                                            <div class="secondary-addto-links actions-secondary" data-role="add-to-links">
                                                <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                                    <?= $addToBlock->setProduct($_item)->getChildHtml() ?>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                    </div>-->
                                <?php endif; ?>
                            </div>
                            <?php endif; ?>
                        </div>
                        <?= ($iterator == count($items)+1) ? '</div>' : '' ?>
                    <?php endforeach ?>
                </div>      
        </div>
        <?php endif; ?>   
        <?php if($type == 'related'):?>
            <h4><strong>RELATED PRODUCTS</strong></h4> <!--TODO: Change to product related -->
        <div class="products wrapper products-<?= $block->escapeHtmlAttr($type) ?>">
                   <span class="slide-nav">
                        <span class="prev-btn"><i class="fas fa-chevron-left"></i></span>
                        <span class="next-btn"><i class="fas fa-chevron-right"></i></span>
                    </span>
                    <ol class="products list items product-items" id="<?php echo $type; ?>">
                        <?php foreach ($items as $_item): ?>
                            <?php $available = ''; ?>
                            <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                                <?php if (!$_item->getRequiredOptions()): ?>
                                    <?php $available = 'related-available'; ?>
                                <?php endif; ?>
                            <?php endif; ?>
                            <?php if ($type == 'related' || $type == 'upsell'): ?>
                                <li class="item product product-item"
                                id="product-item_<?= /* @noEscape */
                                $_item->getId() ?>"
                                data-shuffle-group="<?= $block->escapeHtmlAttr($_item->getPriority()) ?>" >
                                <?= /* @noEscape */
                                $secureRenderer->renderStyleAsTag(
                                    'display:none;',
                                    'li#product-item_' . $_item->getId()
                                ) ?>
                            <?php else: ?>
                                <li class="item product product-item">
                            <?php endif; ?>
                            <div class="product-item-info row <?= /* @noEscape */
                            $available ?>">
                                <?= /* @noEscape */
                                '<!-- ' . $image . '-->' ?>
                               
                                <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                   class="product photo product-item-photo col-5"
                                   style="padding: 15px 0 0 15px;">
                                    <?= $block->getImage($_item, $image)->toHtml() ?>
                                </a>
                                <div class="product details product-item-details col-6">
                                    <strong class="product name product-item-name"><a
                                            class="product-item-link"
                                            title="<?= $block->escapeHtmlAttr($_item->getName()) ?>"
                                            href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>">
                                            <?= $block->escapeHtml($_item->getName()) ?></a>
                                    </strong>
                                    <?php if ($templateType): ?>
                                        <?= $block->getReviewsSummaryHtml($_item, $templateType,false) ?>
                                    <?php endif; ?>
                                    <?php if ((int)$_item->getReviewsCount()==0) : ?>

                                        <div class="rating-summary" id="rating-summary-none">
                                            <div class="rating-result" title="0%">
                                                <span style="width: 0%;"><span>0%</span></span>
                                            </div>
                                        </div>
                                    <?php endif; ?>
                                    <?php ?>
                                    <?= /* @noEscape */
                                    $block->getProductPrice($_item) ?>


                                    <?php if ($canItemsAddToCart && !$_item->isComposite() && $_item->isSaleable()
                                        && $type == 'related'): ?>

                                    <?php endif; ?>

                                    <?php if ($showAddTo || $showCart): ?>
                                        <?php // phpcs:disable ?>
                                        <div class="product actions product-item-actions">
                                            <?php if ($showCart): ?>
                                                <div class="actions-primary">
                                                    <?php if ($_item->isSaleable()): ?>
                                                        <?php if (!$_item->getTypeInstance()->isPossibleBuyFromList($_item)): ?>
                                                            <button
                                                                class="action tocart primary"
                                                                data-mage-init='{"redirectUrl": {"url": "<?= $block->escapeUrl($block->getAddToCartUrl($_item)) ?>"}}'
                                                                type="button"
                                                                title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>">
                                                                <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                            </button>
                                                        <?php else : ?>
                                                            <?php
                                                            /** @var $viewModel PreparePostData */
                                                            $viewModel = $block->getViewModel();
                                                            $postArray = $viewModel->getPostData(
                                                                $block->escapeUrl($block->getAddToCartUrl($_item)),
                                                                ['product' => $_item->getEntityId()]
                                                            );
                                                            $value = $postArray['data'][ActionInterface::PARAM_NAME_URL_ENCODED];
                                                            ?>
                                                            <form data-role="tocart-form"
                                                                  data-product-sku="<?= $block->escapeHtmlAttr($_item->getSku()) ?>"
                                                                  action="<?= $block->escapeUrl($block->getAddToCartUrl($_item)) ?>"
                                                                  method="post">
                                                                <input type="hidden" name="product"
                                                                       value="<?= /* @noEscape */
                                                                       (int)$_item->getEntityId() ?>">
                                                                <input type="hidden"
                                                                       name="<?= /* @noEscape */
                                                                       ActionInterface::PARAM_NAME_URL_ENCODED ?>"
                                                                       value="<?= /* @noEscape */
                                                                       $value ?>">
                                                                <?= $block->getBlockHtml('formkey') ?>
                                                                <button type="submit"
                                                                        title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                                        class="action tocart primary">
                                                                    <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                                </button>
                                                            </form>
                                                        <?php endif; ?>
                                                    <?php else: ?>
                                                        <?php if ($_item->getIsSalable()): ?>
                                                            <div class="stock available">
                                                                <span><?= $block->escapeHtml(__('In stock')) ?></span>
                                                            </div>
                                                        <?php else: ?>
                                                            <div class="stock unavailable">
                                                                <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                                                            </div>
                                                        <?php endif; ?>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                        <?php // phpcs:enable ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                            </li>
                        <?php endforeach ?>
                    </ol>
                </div>
        <?php endif;?>    
    </div>
</div>
<!-- <script type="text/javascript">
    (function () {
        require(["jquery", "jquery/jquery-migrate", "slick"], function ($) {
            jQuery(document).ready(function () {
                jQuery("#related").not('.slick-initialized').slick({

                    rows:2,
                    infinite: true,
                    slidesToShow: 1,
                    slidesToScroll: 1,
                    prevArrow: $(".prev-btn"),
                    nextArrow: $(".next-btn")
                });
            });
        });
    })();
    requirejs(['jquery','Ves_All/lib/owl.carousel/owl.carousel.min'],function(jQuery,owlCarousel){
        (function($) {
            $(window).load(function () {
                $('#owlcarousel_<?=$type?>').owlCarousel({
                  autoPlay: 3000, //Set AutoPlay to 3 seconds

                  items : 3,
                  nav: true,
                  dots: true,
                  navText: ["<i class='fa fa-angle-left' aria-hidden='true'></i>", "<i class='fa fa-angle-right' aria-hidden='true'></i>"],
                  itemsDesktop : [1199,3],
                  itemsDesktopSmall : [900,3], // betweem 900px and 601px
                  itemsTablet: [700,2], // 2 items between 600 and 480
                  itemsMobile : [479,1] , // 1 item between 479 and 0
                  responsiveClass:true,
                        responsive:{
                            0:{
                                items:1,
                                nav:true
                            },
                            600:{
                                items:3,
                                nav:false
                            },
                            1000:{
                                items:5,
                                nav:true,
                                loop:false
                            }
                        }
                });
            });
        })(jQuery);
    });
    // require([
    //     'jquery',
    //     'slick'
    // ], function ($) {
    //     jQuery(document).ready(function () {
    //         jQuery("#related").slick({
    //             rows:1,
    //             infinite: true,
    //             slidesToShow: 1,
    //             slidesToScroll: 1,
    //             responsive: [
    //                 {
    //                     breakpoint: 1280,
    //                     settings: {
    //                         slidesToShow: 3,
    //                         slidesToScroll: 3
    //                     }
    //                 },
    //                 {
    //                     breakpoint: 768,
    //                     settings: {
    //                         slidesToShow: 2,
    //                         slidesToScroll: 2
    //                     }
    //                 },
    //                 {
    //                     breakpoint: 600,
    //                     settings: {
    //                         slidesToShow: 1,
    //                         slidesToScroll: 1
    //                     }
    //                 }
    //             ]
    //         });
    //     });
    // });
</script>    -->
<?php endif;?>