
    <section class="mb-0">
        <div class="row row-sm">
            <div class="col-md-6 col-lg-3">
                <div class="service-widget">
                    <i class="fas fa-shipping-fast"></i>
                    <div class="service-content">
                        <h3 class="service-title">free shipping &amp; return</h3>
                        <p>Free shipping on all orders over $99.</p>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-3">
                <div class="service-widget">
                    <i class="fas fa-dollar-sign"></i>
                    <div class="service-content">
                        <h3 class="service-title">money back guarantee</h3>
                        <p>100% money back guarantee</p>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-3">
                <div class="service-widget">
                    <i class="fas fa-headset"></i>
                    <div class="service-content">
                        <h3 class="service-title">online support 24/7</h3>
                        <p>Lorem ipsum dolor sit amet.</p>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-3">
                <div class="service-widget">
                    <i class="far fa-credit-card"></i>
                    <div class="service-content">
                        <h3 class="service-title">secure payment</h3>
                        <p>Loerm isum dolor sit amet.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

