<div class="menu">
<div class="menu__column">
<p>Account</p>
<ul>
<li><a href="#">My Account</a></li>
<li><a href="#">Track Your Order</a></li>
<li><a href="#">Payment Methods</a></li>
<li><a href="#">Shipping Guide</a></li>
</ul>
</div>
<div class="menu__column">
<p>About</p>
<ul>
<li><a title="About Porto" href="#">About Porto</a></li>
<li><a title="Our Guarantees" href="#">Our Guarantees</a></li>
<li><a title="Terms And Conditions" href="#">Terms And Conditions</a></li>
<li><a title="Privacy Policy">Privacy Policy</a></li>
</ul>
</div>
<div class="menu__column">
<p>Features</p>
<ul>
<li><a href="#">Powerful Admin Panel</a></li>
<li><a href="#">Mobile &amp; Retina Optimized</a></li>
<li><a href="#">Super Fast Porto Theme</a></li>
<li><a href="#">1st Fully working Ajax Theme</a></li>
</ul>
</div>
</div>